name: Local Config
version: 1.0.0
schema: v1

models:
  - name: Gemini Flash
    provider: gemini
    model: gemini-2.0-flash
    apiKey: AQ.Ab8RN6K2gl7QFpB1ynECx1llJijgW85WbcTaRoO_OvLIHmTCEg
    roles:
      - chat
      - edit
      - apply